version: '3'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    links:
      - redis
    volumes:
      - frontend:/frontend
      - ./nginx:/etc/nginx/conf.d
      - media:/media
      - /userfiles:/userfiles
      - /etc/letsencrypt:/etc/letsencrypt
      - redis_data:/redis_data

  backend:
    image: registry.gitlab.com/voimadev/autograf-feature:latest
    restart: always
    env_file:
      - ./envs/prod.env
    command: 'sh /scripts/run.sh'
    #these volumes pass the data from your computer to the docker container
    volumes:
      - frontend:/frontend/build
      - media:/media
      - static:/static
      - /userfiles:/userfiles
    depends_on:
      - postgres
      - redis
    ports:
      - '8000:8000'
    links:
      - redis

  redis:
    image: redis:latest
    ports:
      - '6380:6380'
    restart: always
    command: [ "redis-server", "--bind", "redis", "--port", "6380" ]
    volumes:
      - redis_data:/data

  daphne:
    image: registry.gitlab.com/voimadev/autograf-feature:latest
    command: 'sh /scripts/runDaphne.sh'
    env_file:
      - ./envs/prod.env
    ports:
      - '8001:8001'
    depends_on:
      - postgres
      - redis
    links:
      - redis

  postgres:
    image: postgres:13
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./envs/prod.env
    ports:
    - '5432:5432'

#these volumes create a directory in your computer so that no matter what, they will not be deleted
volumes:
  media:
  static:
  postgres:
  frontend:
  redis_data:
