name: interaction_page
dependencies:
  - python=3.8
  - psycopg2
  - pip
  - pip:
      - Django==3.1.2
      - djangorestframework==3.12.1
      - djangorestframework-simplejwt==4.6.0
      - gunicorn
      - flake8
      - django-cors-headers
      - Pillow==8.0.0
      - requests==2.24.0
      - bs4==0.0.1
      - channels
      - channels_redis
      - daphne
      - python-dateutil