# Generated by Django 3.1.2 on 2021-01-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.TextField(max_length=100)),
                ('post_content', models.TextField(max_length=1000)),
                ('og_title', models.TextField(blank=True, max_length=1000, null=True)),
                ('og_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('og_image', models.TextField(blank=True, max_length=1000, null=True)),
                ('og_url', models.TextField(blank=True, max_length=1000, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/', verbose_name='image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fk_post_image', to='post.post')),
            ],
        ),
    ]
